export const sellList = [
  {
    value: 700,
    version: "5%",
    univalent: 3500,
    num: 5,
    time: "--",
    user: "XXXXXXX",
  },
  {
    value: 700,
    version: "5%",
    univalent: 3500,
    num: 5,
    time: "--",
    user: "XXXXXXX",
  },
  {
    value: 700,
    version: "5%",
    univalent: 3500,
    num: 5,
    time: "--",
    user: "XXXXXXX",
  },
  {
    value: 700,
    version: "5%",
    univalent: 3500,
    num: 5,
    time: "--",
    user: "XXXXXXX",
  },
  {
    value: 700,
    version: "5%",
    univalent: 3500,
    num: 5,
    time: "--",
    user: "XXXXXXX",
  },
  {
    value: 700,
    version: "5%",
    univalent: 3500,
    num: 5,
    time: "--",
    user: "XXXXXXX",
  },
  {
    value: 700,
    version: "5%",
    univalent: 3500,
    num: 5,
    time: "--",
    user: "XXXXXXX",
  },
  {
    value: 700,
    version: "5%",
    univalent: 3500,
    num: 5,
    time: "--",
    user: "XXXXXXX",
  },
  {
    value: 700,
    version: "5%",
    univalent: 3500,
    num: 5,
    time: "--",
    user: "XXXXXXX",
  },
  {
    value: 700,
    version: "5%",
    univalent: 3500,
    num: 5,
    time: "--",
    user: "XXXXXXX",
  },
  {
    value: 700,
    version: "5%",
    univalent: 3500,
    num: 5,
    time: "--",
    user: "XXXXXXX",
  },
];
export const buyList = [
  {
    value: 700,
    version: "5%",
    univalent: 3500,
    num: 5,
    time: "--",
    user: "XXXXXXX",
  },
  {
    value: 700,
    version: "5%",
    univalent: 3500,
    num: 5,
    time: "--",
    user: "XXXXXXX",
  },
  {
    value: 700,
    version: "5%",
    univalent: 3500,
    num: 5,
    time: "--",
    user: "XXXXXXX",
  },
  {
    value: 700,
    version: "5%",
    univalent: 3500,
    num: 5,
    time: "--",
    user: "XXXXXXX",
  },
  {
    value: 700,
    version: "5%",
    univalent: 3500,
    num: 5,
    time: "--",
    user: "XXXXXXX",
  },
  {
    value: 700,
    version: "5%",
    univalent: 3500,
    num: 5,
    time: "--",
    user: "XXXXXXX",
  },
  {
    value: 700,
    version: "5%",
    univalent: 3500,
    num: 5,
    time: "--",
    user: "XXXXXXX",
  },
  {
    value: 700,
    version: "5%",
    univalent: 3500,
    num: 5,
    time: "--",
    user: "XXXXXXX",
  },
  {
    value: 700,
    version: "5%",
    univalent: 3500,
    num: 5,
    time: "--",
    user: "XXXXXXX",
  },
  {
    value: 700,
    version: "5%",
    univalent: 3500,
    num: 5,
    time: "--",
    user: "XXXXXXX",
  },
  {
    value: 700,
    version: "5%",
    univalent: 3500,
    num: 5,
    time: "--",
    user: "XXXXXXX",
  },
];
